sut:
  build: ./test
  links:
    - db
    - auth
    - backend
  environment:
    AUTH_SERVICE_DOMAIN: auth:8000
    BACKEND_SERVICE_DOMAIN: backend:8000

db:
  build: ./db
  environment:
    POSTGRES_USER: auth
    POSTGRES_PASSWORD: auth

auth:
  build: ./auth
  links:
    - db
    - backend
  environment:
    DB_USER: auth
    DB_PASSWORD: auth
    DB_HOST: db
    DB_SCHEMA: authentication
    TARGET_SERVICE_HOST: backend:8000
    DEBUG_MODE: true
  ports:
    - "8000:8000"

backend:
  build: ./backend
