sut:
  build: ./test
  links:
    - db
    - auth
  environment:
    AUTH_SERVICE_DOMAIN: auth:8000

db:
  build: ./db
  environment:
    POSTGRES_USER: auth
    POSTGRES_PASSWORD: auth

auth:
  build: ./auth
  links:
    - db
    - backend
  environment:
    DB_USER: auth
    DB_PASSWORD: auth
    TARGET_SERVICE_HOST: backend:8000
    DEBUG_MODE: true

backend:
  build: ./backend
