sut:
  build: ./test
  links:
    - db
    - auth
    - backend
  environment:
    AUTH_SERVICE_DOMAIN: auth:8000
    BACKEND_SERVICE_DOMAIN: backend:8000
    TEST_JWT: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwiZW1haWwiOiJmb29AYmFyLmNvbSJ9.bgSB8w3HW-LIDllCIOVedS9U3yr9AlWSuhEDgGvulpM

db:
  build: ./db
  environment:
    POSTGRES_USER: auth
    POSTGRES_PASSWORD: auth

auth:
  build: ./auth
  links:
    - db
    - backend
  environment:
    DB_USER: auth
    DB_PASSWORD: auth
    DB_HOST: db
    DB_SCHEMA: authentication
    TARGET_SERVICE_HOST: backend:8000
    DEBUG_MODE: true
    JWT_SECRET: secret
  ports:
    - "8000:8000"

backend:
  build: ./backend
