db:
  build: ./db
  environment:
    POSTGRES_USER: auth
    POSTGRES_PASSWORD: auth

auth:
  build: ./auth
  links:
    - db
    - example-backend
  environment:
    DB_USER: auth
    DB_PASSWORD: auth
    TARGET_SERVICE_HOST: example-backend:8000
    DEBUG_MODE: false

example-backend:
  build: ./example-backend
