sut:
  build: ./test
  links:
    - db
    - auth

db:
  build: ./db
  environment:
    POSTGRES_USER: auth
    POSTGRES_PASSWORD: auth

auth:
  build: ./auth
  links:
    - db
  env:
    DB_USER: auth
    DB_PASSWORD: auth
